name: support
services:
  # FileBrowser
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:v2.23.0
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    hostname: filebrowser
    ports:
      - 10180:80
    volumes:
      - ${DOCKER}/filebrowser/db:/db
      - /:/srv
    network_mode: bridge

  # Homepage
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ${DOCKER}/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    environment:
      HOMEPAGE_ALLOWED_HOSTS: 192.168.1.124:3000 # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts

  # Beszel - system monitor
  # don't forget to install agent
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket

  # Syncthing
  syncthing:
    image: linuxserver/syncthing:latest
    container_name: syncthing
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    restart: unless-stopped
    ports:
      - 8384:8384
      - 22000:22000
      - 22000:22000/udp
      - 21027:21027/udp
    volumes:
      - ${DOCKER}/syncthing/config:/config
      - ${DATA}/syncthing:/syncthing
