version: "3"
services:
  # Jellyfin
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    env_file: media-server.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER}/jellyfin/config:/config
      - ${DOCKER}/jellyfin/cache:/cache
      - ${MEDIA}:/data/media
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    # devices: # iGPU passthrough
      - /dev/dri:/dev/dri

  # qBitTorrent
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    env_file: media-server.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8085
      - TORRENTING_PORT=6881
    volumes:
      - ${DOCKER}/qbittorrent/config:/config
      - ${TORRENTS}:/data/torrents #optional
    ports:
      - 8085:8085
      - 6881:6881
      - 6881:6881/udp

  # Sonarr
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    env_file: media-server.env
    depends_on:
      - prowlarr
      - qbittorrent
    volumes:
      - ${DOCKER}/sonarr/config:/config
      - ${DATA}:/data
    ports:
      - 8989:8989

  # Radarr
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    env_file: media-server.env
    depends_on:
      - prowlarr
      - qbittorrent
    volumes:
      - ${DOCKER}/radarr/config:/config
      - ${DATA}:/data
    ports:
      - 7878:7878

  # Prowlarr
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    env_file: media-server.env
    depends_on:
      - qbittorrent
    volumes:
      - ${DOCKER}/prowlarr/config:/config
    ports:
      - 9696:9696

  # Jellyseerr
  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    restart: unless-stopped
    env_file: media-server.env
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - ${DOCKER}/jellyseerr/config:/app/config

  # Bazarr
  # bazarr:
  #   container_name: bazarr
  #   image: lscr.io/linuxserver/bazarr:latest
  #   restart: unless-stopped
  #   volumes:
  #     - ${DOCKER}/bazarr/config:/config
  #     - ${DATA}:/data
  #   ports:
  #     - 6767:6767

  # Lingarr
  # lingarr:
  #   container_name: lingarr
  #   image: lingarr/lingarr:latest
  #   restart: unless-stopped
  #   volumes:
  #     - ${DATA}:/data
  #     - ${DOCKER}/lingarr/config:/app/config
  #   ports:
  #     - 7676:8080

